package org.example;

public enum TokenType {
    TYPE, START, EXIT, KEYWORD,
    COMMA, SEMICOLON, EQUALS,
    OPEN_BRACKET, CLOSE_BRACKET,
    OPEN_CURLY, CLOSE_CURLY,
    RELOP, ADDOP, MULOP, CONSTANT, LITERAL, IDENTIFIER
}
