package org.example;

public enum TokenType {
    UNEXPECTED, ERROR,
    TYPE, START, EXIT,
    IF, THEN, END, ELSE, WHILE, DO, SCAN, PRINT,
    CONSTANT_FLOAT, CONSTANT_INTEGER,
    COMMA, SEMICOLON, EQUALS, NOT,
    OPEN_ROUND, CLOSE_ROUND,
    OPEN_BRACKET, CLOSE_BRACKET,
    OPEN_CURLY, CLOSE_CURLY,
    RELOP, ADDOP, MULOP, CONSTANT, LITERAL, IDENTIFIER,
    EOF
}
